[project]
site_name = "chickenstats"
site_author = "chicken"
site_url =  "https://chickenstats.com/"
repo_url = "https://github.com/chickenandstats/chickenstats"
site_description = """Technical documentation & reference materials for chickenstats,
    an open-source Python package for scraping & analyzing sports data"""
copyright =  """&copy; 2025 <a href="https://www.chickenandstats.com" target="_blank"
    rel="noopener">Chicken and Stats<br>"""

nav = [
    {"Home" = "index.md"},
    {"User Guide" = [
        "guide/index.md",
        {"Guide" = [
        {"chicken_nhl" = "guide/chicken_nhl/chicken_nhl.md"},
        {"evolving_hockey" = "guide/evolving_hockey/evolving_hockey.md"},
        {"utilities" = "guide/utilities/utilities.md"}]},
        {"Tutorials" = [
        {"Shot Maps" = "guide/tutorials/shot_maps.md"},
        {"Forward lines" = "guide/tutorials/forward_lines.md"},
        {"GSaX" = "guide/tutorials/gsax.md"},
        {"Rolling xG / 60" = "guide/tutorials/rolling_xg.md"},
        {"Lollipop xG" = "guide/tutorials/lollipop.md"},
        {"Network graphs" = "guide/tutorials/network.md"},
        {"4 Nations Face-Off" = "guide/tutorials/four_nations.md"},
        {"High-danger chances" = "guide/tutorials/high_danger.md"},
        {"Matchups" = "guide/tutorials/matchups.md"},
        ]},
        {"Examples" = [
            {"Gallery" = "guide/examples/gallery.md"},
            {"Original Research" = "guide/examples/original_research.md"},
        ]},
        ]},
  {"Reference" = [
      "reference/index.md",
      {"chicken_nhl" = [
          {"scrape" = "reference/chicken_nhl/scrape.md"},]},
      {"evolving_hockey" = [
          {"stats" = "reference/evolving_hockey/stats.md"},]},
      {"Fancy stats" = [
        {"Score and venue" = "reference/fancy_stats/score_adjustments.md"},
        {"Danger and high-danger" = "reference/fancy_stats/high_danger.md"},]}]},
      {"xG Model" = [
          "xg_model/index.md",
          {"The Model" = [
              {"Overview" = "xg_model/overview.md"},]},]},
  {"Blog" = "https://blog.chickenstats.com"},
  {"Contribute" = [
      "contribute/index.md",
      {"Roadmap" = "contribute/roadmap.md"},
      {"Known Issues" = "contribute/known_issues.md"},
      {"Under the Hood" = [
          {"Design" = "contribute/backend/design.md"},
          {"chicken_nhl" = "contribute/backend/chicken_nhl.md"},
          {"evolving_hockey" = "contribute/backend/evolving_hockey.md"},]}]}]

[project.extra.analytics]
provider = "google"
property = "G-S4K9S6V8XX"

[project.theme]
favicon = "assets/site_images/favicon.png"
#logo = "assets/site_images/logo-outline.png"
logo = "assets/site_images/favicon.png"
custom_dir = "docs/overrides"
features = [
    "content.footnote.tooltips",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.tabs.link",
    "header.autohide",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    "navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    "navigation.top",
    "navigation.footer",
    "search.highlight",
    "toc.follow",
    "toc.integrate",
]

[project.theme.icon]
repo = "fontawesome/brands/github"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "material/link"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "material/toggle-switch"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "material/toggle-switch-off-outline"
toggle.name = "Switch to system preference"

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"
options.custom_icons = ["docs/overrides/.icons"]

[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.tables]

[project.markdown_extensions.pymdownx.blocks.caption]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]

[project.markdown_extensions.pymdownx.tabbed.slugify]
object = "pymdownx.slugs.slugify"
kwds = { case = "lower" }

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["src/chickenstats"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
show_root_heading = true
show_source = true
show_root_toc_entry = true
show_root_full_path = false
separate_signature = true
merge_init_into_class = false
inherited_members = true

[project.markdown_extensions.toc]
toc_depth = 4


